### ISSUE TITLE
When will you release the code?

### ISSUE THREAD

**Issue by LZ-QWQ** [rpmsnu/sRGB-TIR#1]
Thank you for your great work in RGB to TIR translation, and when will you release the code?

**Comment by rpmsnu** [comment]
Hi LZ! 

Thank you for taking an interest in our code!

Currently, all of the authors are pretty busy dealing with other research work, so we don't currently have the time capacity to polish up the git and publish the code!

Things are going to settle down a bit in April, so we hopefully will release the code and the translation tool.

Stay tuned!

Many Thanks!

DongGuw

**Comment by rpmsnu** [comment]
> Thank you for your great work in RGB to TIR translation, and when will you release the code?

Hi LZ!

Thanks for the long wait!

We have now uploaded the RGB-to-TIR translation inference code as well as the trained weights for usage!

If you are interested, please give it a try :) 

Again, thanks for being patient!


DongGuw
