### ISSUE TITLE
Gradients: inf or nan in tensor

### ISSUE THREAD

**Issue by SiBensberg** [rpmsnu/sRGB-TIR#7]
Hi,
I used the FLIR dataset to try out the training. From time to time the error above happens and all model parameters are nan's. Could ou observe similiar behaviour? 
I fixed it through catching nan values and clipping gradients.

**Comment by ckavak** [comment]
Hello,

I have the same problem right now. I followed your solution however still getting nan values.

Could you please share your codes regarding clipping gradients ?
